from fpdf import FPDF

class DietPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(0, 150, 75)
        self.cell(0, 10, "AI Personalized Diet Recommendation System", border=False, new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "Personalized Nutrition & Food Details Report", border=False, new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by AI Diet Recommendation System", align="C")


def clean_text(text):
    """Replace unsupported unicode characters for standard FPDF fonts."""
    if not isinstance(text, str):
        text = str(text)
    return text.encode("latin-1", "replace").decode("latin-1")


def generate_pdf_report(goal, bmi, water, protein, bmr, tdee, foods_df):
    pdf = DietPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Section: Health Metrics Overview
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(240, 248, 240)
    pdf.set_text_color(0, 100, 50)
    pdf.cell(0, 7, "  User Health & Calorie Summary", border=True, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(0, 0, 0)
    metrics_text = (
        f"- Recommended Goal: {goal}\n"
        f"- Body Mass Index (BMI): {bmi}\n"
        f"- Daily Water Requirement: {water} Liters\n"
        f"- Daily Protein Need: {protein} g\n"
        f"- Basal Metabolic Rate (BMR): {round(bmr)} kcal\n"
        f"- Total Daily Energy Expenditure (TDEE): {round(tdee)} kcal"
    )
    pdf.multi_cell(0, 5, metrics_text)
    pdf.ln(4)

    # Section: Recommended Foods Table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(240, 248, 240)
    pdf.set_text_color(0, 100, 50)
    pdf.cell(0, 7, "  Recommended Food Details", border=True, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    col_widths = [65, 25, 25, 25, 25, 25]  # Total = 190 mm
    headers = ["Food Name", "Calories", "Protein(g)", "Carbs(g)", "Fat(g)", "Fiber(g)"]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(0, 150, 75)
    pdf.set_text_color(255, 255, 255)

    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 7, h, border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(0, 0, 0)

    fill = False
    for _, row in foods_df.iterrows():
        pdf.set_fill_color(245, 245, 245) if fill else pdf.set_fill_color(255, 255, 255)

        food_name = clean_text(str(row["food"]))[:35]
        cals = str(round(row.get("calories", 0), 1))
        prot = str(round(row.get("protein", 0), 1))
        carbs = str(round(row.get("carbs", 0), 1))
        fat = str(round(row.get("fat", 0), 1))
        fiber = str(round(row.get("fiber", 0), 1))

        pdf.cell(col_widths[0], 6, f" {food_name}", border=1, fill=fill)
        pdf.cell(col_widths[1], 6, cals, border=1, align="C", fill=fill)
        pdf.cell(col_widths[2], 6, prot, border=1, align="C", fill=fill)
        pdf.cell(col_widths[3], 6, carbs, border=1, align="C", fill=fill)
        pdf.cell(col_widths[4], 6, fat, border=1, align="C", fill=fill)
        pdf.cell(col_widths[5], 6, fiber, border=1, align="C", fill=fill)
        pdf.ln()
        fill = not fill

    return bytes(pdf.output())


def generate_meal_plan_pdf(meal_plan_df, goal, tdee):
    pdf = DietPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(240, 248, 240)
    pdf.set_text_color(0, 100, 50)
    pdf.cell(0, 7, f"  3-Month Meal Plan Details ({goal} - {tdee} kcal/day)", border=True, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    col_widths = [22, 52, 52, 52, 12]  # Total = 190 mm
    headers = ["Date", "Breakfast", "Lunch", "Dinner", "Cals"]

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(0, 150, 75)
    pdf.set_text_color(255, 255, 255)

    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 6, h, border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(0, 0, 0)

    fill = False
    for _, row in meal_plan_df.iterrows():
        pdf.set_fill_color(245, 245, 245) if fill else pdf.set_fill_color(255, 255, 255)

        date_str = str(row.get("Date", ""))
        b_str = clean_text(str(row.get("Breakfast", "")))[:28]
        l_str = clean_text(str(row.get("Lunch", "")))[:28]
        d_str = clean_text(str(row.get("Dinner", "")))[:28]
        cals_str = str(int(row.get("Calories", 0)))

        pdf.cell(col_widths[0], 5, date_str, border=1, align="C", fill=fill)
        pdf.cell(col_widths[1], 5, f" {b_str}", border=1, fill=fill)
        pdf.cell(col_widths[2], 5, f" {l_str}", border=1, fill=fill)
        pdf.cell(col_widths[3], 5, f" {d_str}", border=1, fill=fill)
        pdf.cell(col_widths[4], 5, cals_str, border=1, align="C", fill=fill)
        pdf.ln()
        fill = not fill

    return bytes(pdf.output())
